alias ll='ls -l'
alias la='ls -a'
alias lla='ls -la'
alias ddd='rm -rfv ~/Library/Developer/Xcode/DerivedData && rm -rfv ~/Library/Caches/appCode31/DerivedData'
alias cls='clear'

alias g='git'
alias gc='git commit'
alias gs='git status'
alias gf='git fetch'
alias gcof='git checkout $(git branch -a | fzf)'
alias gmm='git merge --ff origin/main'
alias gca='git commit -a'
alias gcm='git checkout main'
alias gsu='git submodule update'

alias be='bundle exec'

alias v='vagrant'
alias vu='vagrant up'
alias vh='vagrant halt'
alias vdf='vagrant destroy -f'

alias w='cd ~/Documents/GoReport'
alias dc='w; cd ./docker-compose-files'
