alias bb='bbedit --project'
alias ll='ls -l'
alias la='ls -a'
alias lla='ls -la'
alias ddd='rm -rfv ~/Library/Developer/Xcode/DerivedData'
alias cls='clear'

alias g='git'
alias gs='git status'
alias gf='git fetch'
alias gmm='git merge --ff origin/master'
alias gca='git commit -a'
alias gcm='git checkout master'
