alias ll='ls -l'
alias la='ls -a'
alias lla='ls -la'
alias ddd='rm -rfv ~/Library/Developer/Xcode/DerivedData && rm -rfv ~/Library/Caches/appCode31/DerivedData'
alias cls='clear'

alias g='git'
alias gc='git commit'
alias gs='git status'
alias gf='git fetch'
alias gmm='git merge --ff origin/master'
alias gca='git commit -a'
alias gcm='git checkout master'
alias gsu='git submodule update'

alias be='bundle exec'

alias v='vagrant'
alias vu='vagrant up'
alias vh='vagrant halt'
alias vdf='vagrant destroy -f'
